[package]
name = "pzip"
version = "0.2.0"
authors = ["ucyo <cayoglu@me.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"

[dev-dependencies]
criterion = "0.2"
rand="0.6.4"

[["bench"]]
name = "arithmetics"
harness = false
