[package]
name = "pzip"
version = "0.2.0"
authors = ["ucyo <cayoglu@me.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
log = "0.4.6"
env_logger = "0.6.0"
bit-vec = "0.4.4"
rand="0.6.4"

[dev-dependencies]
criterion = "0.2"

[["bench"]]
name = "arithmetics"
harness = false
