[package]
name = "pzip"
version = "0.1.0"
authors = ["ucyo <cayoglu@me.com>"]
edition = "2018"

[dependencies]
byteorder = "1.2.7"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "pzip_benchmark"
harness = false
